// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsNotifier.Data;

#nullable disable

namespace NewsNotifier.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250619085440_AddDescriptionColumnToNewsArticle")]
    partial class AddDescriptionColumnToNewsArticle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewsAggregator.Server.Models.Entities.ExternalApiConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastAccessed")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExternalApis");
                });

            modelBuilder.Entity("NewsNotifier.Models.Entities.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("NewsNotifier.Models.Entities.NewsArticle", b =>
                {
                    b.Property<int>("ArticleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleID"));

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dislikes")
                        .HasColumnType("int");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArticleID");

                    b.HasIndex("CategoryID");

                    b.ToTable("NewsArticles");
                });

            modelBuilder.Entity("NewsNotifier.Models.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<int>("ArticleID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.HasIndex("ArticleID");

                    b.HasIndex("UserID");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("NewsNotifier.Models.Entities.NotificationConfig", b =>
                {
                    b.Property<int>("ConfigID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Keywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ConfigID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("UserID");

                    b.ToTable("NotificationConfig");
                });

            modelBuilder.Entity("NewsNotifier.Models.Entities.SavedArticle", b =>
                {
                    b.Property<int>("SavedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SavedID"));

                    b.Property<int>("ArticleID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SavedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("SavedID");

                    b.HasIndex("ArticleID");

                    b.HasIndex("UserID");

                    b.ToTable("SavedArticles");
                });

            modelBuilder.Entity("NewsNotifier.Models.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("NewsNotifier.Models.Entities.AdminUser", b =>
                {
                    b.HasBaseType("NewsNotifier.Models.Entities.User");

                    b.HasDiscriminator().HasValue("AdminUser");
                });

            modelBuilder.Entity("NewsNotifier.Models.Entities.NormalUser", b =>
                {
                    b.HasBaseType("NewsNotifier.Models.Entities.User");

                    b.HasDiscriminator().HasValue("NormalUser");
                });

            modelBuilder.Entity("NewsNotifier.Models.Entities.NewsArticle", b =>
                {
                    b.HasOne("NewsNotifier.Models.Entities.Category", null)
                        .WithMany("NewsArticles")
                        .HasForeignKey("CategoryID");
                });

            modelBuilder.Entity("NewsNotifier.Models.Entities.Notification", b =>
                {
                    b.HasOne("NewsNotifier.Models.Entities.NewsArticle", "NewsArticle")
                        .WithMany("Notifications")
                        .HasForeignKey("ArticleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsNotifier.Models.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsArticle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewsNotifier.Models.Entities.NotificationConfig", b =>
                {
                    b.HasOne("NewsNotifier.Models.Entities.Category", "Category")
                        .WithMany("NotificationConfigs")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsNotifier.Models.Entities.User", "User")
                        .WithMany("NotificationConfigs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewsNotifier.Models.Entities.SavedArticle", b =>
                {
                    b.HasOne("NewsNotifier.Models.Entities.NewsArticle", "NewsArticle")
                        .WithMany("SavedArticles")
                        .HasForeignKey("ArticleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsNotifier.Models.Entities.User", "User")
                        .WithMany("SavedArticles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsArticle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewsNotifier.Models.Entities.Category", b =>
                {
                    b.Navigation("NewsArticles");

                    b.Navigation("NotificationConfigs");
                });

            modelBuilder.Entity("NewsNotifier.Models.Entities.NewsArticle", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("SavedArticles");
                });

            modelBuilder.Entity("NewsNotifier.Models.Entities.User", b =>
                {
                    b.Navigation("NotificationConfigs");

                    b.Navigation("Notifications");

                    b.Navigation("SavedArticles");
                });
#pragma warning restore 612, 618
        }
    }
}
